# Generated by Django 4.2.16 on 2025-01-11 19:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(
                verbose_name='image',
                max_length=255,
                blank=True,
                null=True
            ),
        ),
    ]
