# Generated by Django 4.2.16 on 2025-01-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blog.post'),
        ),
    ]
