# Generated by Django 4.2.16 on 2025-01-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_like_count_post_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_users',
        ),
    ]
