# Generated by Django 4.2.16 on 2024-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_event_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
