# Generated by Django 4.2.16 on 2025-01-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
